version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run: echo "prefix=$HOME/.local" > ~/.npmrc
      - run: export "PATH=$PATH:$HOME/.local/bin"
      - run: npm i -g origami-build-tools@^7
      - run: origami-build-tools install
      - run: origami-build-tools demo --demo-filter pa11y --suppress-errors
      - run: origami-build-tools verify
      - run: origami-build-tools test
      - run: git clean -fxd
      - run: npx occ build --semver 0.0.0
      - run: origami-build-tools --ignore-bower install
      - run: origami-build-tools --ignore-bower test
  publish:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npx occ build --semver ${VERSION##v}
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run: npm publish
workflows:
  version: 2
  test:
    jobs:
      - test
      - publish_to_npm:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/