version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run: npm config set prefix "$HOME/.local"
      - run: npm i -g origami-build-tools@^7
      - run: $HOME/.local/bin/obt install
      - run: $HOME/.local/bin/obt demo --demo-filter pa11y --suppress-errors
      - run: $HOME/.local/bin/obt verify
      - run: $HOME/.local/bin/obt test
workflows:
  version: 2
  test:
    jobs:
      - test
