version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run: npx origami-build-tools@^7 install
      - run: npx origami-build-tools@^7 demo --demo-filter pa11y --suppress-errors
      - run: npx origami-build-tools@^7 verify
      - run: npx origami-build-tools@^7 test
      - run: git clean -fxd
      - run: npx occ build --semver 0.0.0
      - run: npx origami-build-tools@^7 install --ignore-bower
      - run: npx origami-build-tools@^7 test --ignore-bower
  publish:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npx occ build --semver ${VERSION##v}
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run: npm publish --dry-run
workflows:
  version: 2
  test:
    jobs:
      - test
      - publish_to_npm:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/